### PR TITLE
#16 added an explicit convertion to the Unix file system separtors

### PR DESCRIPTION
**Pull request by adko-pl**
@dmarkov please find a reviewer

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll find someone to review this PR soon

**Comment by dmarkov** [comment]
@krzyk please review

**Comment by krzyk** [comment]
@adko-pl build doesn't pass on travis

**Comment by adko-pl** [comment]
@krzyk fixed the issues

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@krzyk Many thanks! **17 mins** were added to your account in Transaction ID `50596370`. +17 added to your rating, current score is: [+2365](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
